imports:
    - { resource: tables.yml }
services:
    dmzx.buttonmenu.listener:
        class: dmzx\buttonmenu\event\listener
        arguments:
            - '@service_container'
            - '@config'
            - '@language'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '%dmzx.buttonmenu.table.menu_buttons%'
            - '%dmzx.buttonmenu.table.menu_styles%'
        tags:
            - { name: event.listener }
